spring.application.name=vgashop
spring.datasource.url=jdbc:mysql://localhost:3306/vga_store
spring.datasource.username=root
spring.datasource.password=12022005@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
